2021-10-08 04:07:02 UTC Syncing #13375934 0x05ed…a053     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   34 Qed Ancient:#12969651 LI:#13375965   17/25 peers      2 MiB chain   10 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-10-08 04:07:16 UTC Syncing #13375936 0xb325…390c     0.40 blk/s   91.4 tx/s    6.0 Mgas/s      0+   32 Qed Ancient:#12969653 LI:#13375965   17/25 peers      2 MiB chain    9 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-10-08 04:07:16 UTC Syncing #13375936 0xb325…390c     0.20 blk/s   45.7 tx/s    3.0 Mgas/s      0+   32 Qed Ancient:#12969653 LI:#13375965   17/25 peers      2 MiB chain    9 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-10-08 04:07:28 UTC Syncing #13375936 0xb325…390c     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   32 Qed Ancient:#12969653 LI:#13375965   17/25 peers      2 MiB chain    9 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-10-08 04:07:28 UTC Syncing #13375936 0xb325…390c     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   32 Qed Ancient:#12969653 LI:#13375965   17/25 peers      2 MiB chain    9 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-10-08 04:07:28 UTC Syncing #13375936 0xb325…390c     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   32 Qed Ancient:#12969653 LI:#13375965   17/25 peers      2 MiB chain    9 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-10-08 04:07:32 UTC Syncing #13375936 0xb325…390c     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   34 Qed Ancient:#12969653 LI:#13375967   14/25 peers      2 MiB chain   10 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-10-08 04:07:37 UTC Syncing #13375936 0xb325…390c     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   34 Qed Ancient:#12969653 LI:#13375967   12/25 peers      2 MiB chain   10 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-10-08 04:07:42 UTC Syncing #13375936 0xb325…390c     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   34 Qed Ancient:#12969653 LI:#13375967   15/25 peers      2 MiB chain   10 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-10-08 04:07:47 UTC Syncing #13375936 0xb325…390c     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   35 Qed Ancient:#12969653 LI:#13375968   17/25 peers      2 MiB chain   10 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-10-08 04:07:52 UTC Panic occured, see stderr for details


====================

   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   5: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   6: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   7: <ethcore_blockchain::blockchain::BlockChain as ethcore_blockchain::blockchain::BlockProvider>::block_header_data
   8: <ethcore::client::client::Client as ethcore::client::traits::BlockInfo>::block_header
   9: core::ops::function::Fn::call
  10: ethcore_sync::chain::supplier::SyncSupplier::dispatch_packet
  11: <ethcore_sync::api::SyncProtocolHandler as ethcore_network::NetworkProtocolHandler>::read
  12: <ethcore_network_devp2p::host::Host as ethcore_io::IoHandler<ethcore_network::NetworkIoMessage>>::stream_readable
  13: ethcore_io::worker::Worker::new::{{closure}}::{{closure}}
  14: <futures::future::loop_fn::LoopFn<A,F> as futures::future::Future>::poll
  15: std::sys_common::backtrace::__rust_begin_short_backtrace
  16: core::ops::function::FnOnce::call_once{{vtable.shim}}
  17: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
  18: start_thread
  19: __clone


Thread 'Worker devp2p1' panicked at 'Low level database error when fetching block header data. Some issue with disk?: Custom { kind: Other, error: "IO error: While open a file for random read: /data/blockchain/eth-data/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/1774463.sst: No such file or directory" }', crates/ethcore/blockchain/src/blockchain.rs:335

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new


2021-10-08 04:07:52 UTC Panic occured, see stderr for details


====================

   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   5: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   6: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   7: <journaldb::overlayrecentdb::OverlayRecentDB as hash_db::HashDB<keccak_hasher::KeccakHasher,elastic_array::ElasticArray128<u8>>>::get
   8: <ethcore::account_db::AccountDB as hash_db::HashDB<keccak_hasher::KeccakHasher,elastic_array::ElasticArray128<u8>>>::get
   9: <&mut dyn hash_db::HashDB<H,T> as hash_db::HashDBRef<H,T>>::get
  10: ethcore::state::account::Account::get_and_cache_storage
  11: ethcore::state::State<B>::storage_at
  12: <ethcore::externalities::Externalities<T,V,B> as vm::ext::Ext>::storage_at
  13: evm::interpreter::Interpreter<Cost>::exec_instruction
  14: <evm::interpreter::Interpreter<Cost> as vm::Exec>::exec
  15: ethcore::executive::CallCreateExecutive::exec
  16: ethcore::executive::CallCreateExecutive::consume
  17: ethcore::executive::Executive<B>::call_with_stack_depth
  18: ethcore::executive::Executive<B>::transact
  19: ethcore::block::OpenBlock::push_transaction
  20: ethcore::client::client::Importer::import_verified_blocks
  21: <ethcore_service::service::ClientIoHandler as ethcore_io::IoHandler<ethcore::client::io_message::ClientIoMessage>>::message
  22: ethcore_io::worker::Worker::new::{{closure}}::{{closure}}
  23: <futures::future::loop_fn::LoopFn<A,F> as futures::future::Future>::poll
  24: std::sys_common::backtrace::__rust_begin_short_backtrace
  25: core::ops::function::FnOnce::call_once{{vtable.shim}}
  26: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
  27: start_thread
  28: __clone


Thread 'Worker Client0' panicked at 'Low-level database error. Some issue with your hard disk?: Custom { kind: Other, error: "IO error: While open a file for random read: /data/blockchain/eth-data/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/1715848.sst: No such file or directory" }', crates/db/journaldb/src/overlayrecentdb.rs:180

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new


2021-10-08 04:07:52 UTC Finishing work, please wait...
2021-10-08 04:07:52 UTC Panic occured, see stderr for details


====================

   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   5: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   6: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   7: <ethcore_blockchain::blockchain::BlockChain as ethcore_blockchain::blockchain::BlockProvider>::transaction_address
   8: ethcore::client::client::Client::transaction_address
   9: ethcore_miner::pool::queue::TransactionQueue::import::{{closure}}
  10: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  11: alloc::vec::source_iter_marker::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  12: ethcore_miner::pool::queue::TransactionQueue::import
  13: ethcore::client::client::IoChannelQueue::queue::{{closure}}
  14: <ethcore_service::service::ClientIoHandler as ethcore_io::IoHandler<ethcore::client::io_message::ClientIoMessage>>::message
  15: ethcore_io::worker::Worker::new::{{closure}}::{{closure}}
  16: <futures::future::loop_fn::LoopFn<A,F> as futures::future::Future>::poll
  17: std::sys_common::backtrace::__rust_begin_short_backtrace
  18: core::ops::function::FnOnce::call_once{{vtable.shim}}
  19: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
  20: start_thread
  21: __clone


Thread 'Worker Client3' panicked at 'db get failed, key: [2, 154, 234, 106, 154, 232, 50, 246, 185, 16, 58, 9, 75, 39, 209, 185, 56, 152, 52, 81, 108, 110, 20, 211, 166, 90, 165, 182, 101, 159, 127, 108, 108]: Custom { kind: Other, error: "IO error: While open a file for random read: /data/blockchain/eth-data/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/1702799.sst: No such file or directory" }', /data/blockchain/openethereum/crates/db/db/src/db.rs:294

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new


2021-10-08 04:07:53 UTC Panic occured, see stderr for details


====================

   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   5: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   6: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   7: <ethcore_blockchain::blockchain::BlockChain as ethcore_blockchain::blockchain::BlockProvider>::transaction_address
   8: ethcore::client::client::Client::transaction_address
   9: ethcore_miner::pool::queue::TransactionQueue::import::{{closure}}
  10: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  11: alloc::vec::source_iter_marker::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  12: ethcore_miner::pool::queue::TransactionQueue::import
  13: ethcore::client::client::IoChannelQueue::queue::{{closure}}
  14: <ethcore_service::service::ClientIoHandler as ethcore_io::IoHandler<ethcore::client::io_message::ClientIoMessage>>::message
  15: ethcore_io::worker::Worker::new::{{closure}}::{{closure}}
  16: <futures::future::loop_fn::LoopFn<A,F> as futures::future::Future>::poll
  17: std::sys_common::backtrace::__rust_begin_short_backtrace
  18: core::ops::function::FnOnce::call_once{{vtable.shim}}
  19: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
  20: start_thread
  21: __clone


Thread 'Worker Client1' panicked at 'db get failed, key: [2, 30, 94, 162, 16, 112, 85, 185, 56, 248, 118, 36, 156, 209, 35, 9, 139, 43, 8, 105, 186, 251, 100, 229, 129, 117, 50, 70, 241, 61, 185, 64, 118]: Custom { kind: Other, error: "IO error: While open a file for random read: /data/blockchain/eth-data/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/1264744.sst: No such file or directory" }', /data/blockchain/openethereum/crates/db/db/src/db.rs:294

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new


2021-10-08 04:07:55 UTC Panic occured, see stderr for details


====================

   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   5: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   6: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   7: <journaldb::overlayrecentdb::OverlayRecentDB as hash_db::HashDB<keccak_hasher::KeccakHasher,elastic_array::ElasticArray128<u8>>>::get
   8: <&mut dyn hash_db::HashDB<H,T> as hash_db::HashDBRef<H,T>>::get
   9: trie_db::lookup::Lookup<H,C,Q>::look_up
  10: ethcore::state::State<B>::nonce
  11: ethcore::client::traits::Nonce::latest_nonce
  12: <ethcore::miner::pool_client::CachedNonceClient<C> as ethcore_miner::pool::client::NonceClient>::account_nonce
  13: ethcore_miner::pool::queue::TransactionQueue::import::{{closure}}
  14: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  15: alloc::vec::source_iter_marker::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  16: ethcore_miner::pool::queue::TransactionQueue::import
  17: ethcore::client::client::IoChannelQueue::queue::{{closure}}
  18: <ethcore_service::service::ClientIoHandler as ethcore_io::IoHandler<ethcore::client::io_message::ClientIoMessage>>::message
  19: ethcore_io::worker::Worker::new::{{closure}}::{{closure}}
  20: <futures::future::loop_fn::LoopFn<A,F> as futures::future::Future>::poll
  21: std::sys_common::backtrace::__rust_begin_short_backtrace
  22: core::ops::function::FnOnce::call_once{{vtable.shim}}
  23: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
  24: start_thread
  25: __clone


Thread 'Worker Client2' panicked at 'Low-level database error. Some issue with your hard disk?: Custom { kind: Other, error: "IO error: While open a file for random read: /data/blockchain/eth-data/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/1716129.sst: No such file or directory" }', crates/db/journaldb/src/overlayrecentdb.rs:180

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new


Error: 1