2021-06-08 14:17:02 UTC Imported #12594375 0x504e…e48d (178 txs, 14.98 Mgas, 4947 ms, 55.67 KiB)
2021-06-08 14:17:09 UTC Imported #12594376 0xd82d…fc8a (166 txs, 14.95 Mgas, 6420 ms, 59.20 KiB)
2021-06-08 14:17:12 UTC  32/50 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
2021-06-08 14:17:30 UTC Imported #12594377 0x2602…94df (160 txs, 14.98 Mgas, 4138 ms, 67.09 KiB)
2021-06-08 14:17:44 UTC  32/50 peers      6 MiB chain  183 KiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-06-08 14:17:53 UTC Imported #12594380 0x2f88…edee (189 txs, 14.99 Mgas, 7332 ms, 49.10 KiB)
2021-06-08 14:18:02 UTC Imported #12594381 0x0aa6…ed05 (176 txs, 14.97 Mgas, 6926 ms, 55.59 KiB)
2021-06-08 14:18:11 UTC Imported #12594382 0xb785…7c60 (123 txs, 14.96 Mgas, 7707 ms, 61.43 KiB)
2021-06-08 14:18:16 UTC  32/50 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
2021-06-08 14:18:20 UTC Imported #12594383 0x0b55…16b0 (195 txs, 14.80 Mgas, 5160 ms, 46.33 KiB)
2021-06-08 14:18:37 UTC Imported #12594384 0x675f…3834 (142 txs, 14.99 Mgas, 5648 ms, 55.32 KiB)
2021-06-08 14:18:49 UTC  32/50 peers      6 MiB chain  226 KiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-06-08 14:18:53 UTC Imported #12594385 0x8191…8618 (154 txs, 14.98 Mgas, 2123 ms, 68.88 KiB)
2021-06-08 14:19:16 UTC Panic occured, see stderr for details


====================

stack backtrace:
   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/panicking.rs:595
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/panicking.rs:497
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/sys_common/backtrace.rs:141
   4: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/panicking.rs:493
   5: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/core/src/panicking.rs:92
   6: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/core/src/option.rs:1300
   7: <ethcore_network_devp2p::host::Host as ethcore_io::IoHandler<ethcore_network::NetworkIoMessage>>::update_stream
   8: mio::deprecated::event_loop::EventLoop<H>::run
   9: std::sys_common::backtrace::__rust_begin_short_backtrace
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
  11: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/sys/unix/thread.rs:71
  12: start_thread
  13: __clone


Thread '<unnamed>' panicked at 'Error reregistering UDP socket: Os { code: 9, kind: Other, message: "Bad file descriptor" }', crates/net/network-devp2p/src/host.rs:1425

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new


2021-06-08 14:19:16 UTC Finishing work, please wait...
2021-06-08 14:19:16 UTC Error on IO service shutdown: NotifyError::Closed(..)
Error: 1